name: Lint and Test

on:
  pull_request:
    branches: 
      - master

jobs:
  Lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.11.4
      uses: actions/setup-python@v1
      with:
        python-version: 3.11.4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install flake8
        python -m pip install bandit
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --show-source --statistics --select=E9,F63,F7,F82
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=79 --statistics
    - name: Security Test with bandit
      run: |
        bandit -ll -s B507,B601 . -r

  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.11.4
      uses: actions/setup-python@v1
      with:
        python-version: 3.11.4
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
        python -m pip install pytest
    - name: Test with Pytest
      run: |
        python -m pytest -v
